spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vstore
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    clean-disabled: true   # <- evita clean acidental
    baseline-on-migrate: true
    validate-on-migrate: true

jwt:
  secret: ${JWT_SECRET}